# Generated by Django 3.0 on 2021-09-26 09:57

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
    ]


from django.apps import apps as global_apps
from django.db import migrations

def forwards(apps, schema_editor):
    try:
        OldModelProfile = apps.get_model('oc_lettings_site', 'OldProfile')
    except LookupError:
        # The old app isn't installed.
        return

    NewModelProfile = apps.get_model('profiles', 'Profile')
    NewModelProfile.objects.bulk_create(
        NewModelProfile(
                user=old_object.user,
                favorite_city=old_object.favorite_city       
            )
        for old_object in OldModelProfile.objects.all()
    )


class Migration(migrations.Migration):
    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
    dependencies = [
        ('oc_lettings_site', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    if global_apps.is_installed('oc_lettings_site'):
        dependencies.append(('oc_lettings_site', '0001_initial'))
        