version: "2.1"
services:
  web:
    image: fortranvba/dap13:latest
    environment:
      - DJANGO_SK="isdgsihdihfihio"
      - DEBUG_DJANGO="True"
    command:
      - python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
