version: "2.1"
services:
  tests:
    image: fortranvba/dap13:latest
    command: python manage.py test
    depends_on:
      - linter
  linter:
    build:
      context: .
    image: fortranvba/dap13:latest
    command: flake8
