# Generated by Django 3.0 on 2021-09-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
    ]


from django.apps import apps as global_apps
from django.db import migrations

def forwards(apps, schema_editor):
    try:
        OldModelAddress = apps.get_model('oc_lettings_site', 'Address')
        OldModelLetting = apps.get_model('oc_lettings_site', 'Letting')
    except LookupError:
        # The old app isn't installed.
        return

    NewModelAddress = apps.get_model('lettings', 'Address')
    NewModelAddress.objects.bulk_create(
        NewModelAddress(
            number=old_object.number,
            street=old_object.street,
            city=old_object.city,
            state=old_object.state,
            zip_code=old_object.zip_code,
            country_iso_code=old_object.country_iso_code
            )
        for old_object in OldModelAddress.objects.all()
    )

    NewModelLetting = apps.get_model('lettings', 'Letting')
    NewModelLetting.objects.bulk_create(
        NewModelLetting(
            title=old_object.title,
            address=NewModelAddress.objects.get(
                number=old_object.address.number, 
                street=old_object.address.street, 
                city=old_object.address.city,
                state=old_object.address.state,
                zip_code=old_object.address.zip_code,
                country_iso_code=old_object.address.country_iso_code
                )
            )
        for old_object in OldModelLetting.objects.all()
    )

class Migration(migrations.Migration):
    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
    dependencies = [
        ('oc_lettings_site', '0001_initial'),
        ('lettings', '0001_initial'),
    ]

    if global_apps.is_installed('oc_lettings_site'):
        dependencies.append(('oc_lettings_site', '0001_initial'))
        