version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  heroku_deploy:
    jobs:
      - build_main:
          filters:
            branches:
              only: main
      - heroku/deploy-via-git:
          requires:
            - build_main
            - test_main
          filters:
            branches:
              only: main

jobs:
  build_main:
    docker:
      - image: docker:18.09-git
        auth:
          username: fortranvba
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image from file
          command: |
            docker build -t fortranvba/dap13:dap13prod .
      - run:
          name: Run linter
          command: |
            docker-compose -f ./docker-compose.test_linter.yml up

  test_main:
    docker:
      - image: fortranvba/dap13:dap13prod
    steps:
      - run:
          name: Running linter
          command: |
            flake8
      - run:
          name: Running tests
          command: |
            python manage.py test  
      - store_artifacts:
          path: test-reports/
          destination: python_app
      - deploy:
          name: Push application Docker image
          command: |
            docker push fortranvba/dap13:dap13prod
