version: 2

orbs:
  heroku: circleci/heroku@0.0.10

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build

jobs:
  build:
    docker:
      - image: fortranvba/dap13:dap13prod
        auth:
          username: fortranvba
          password: $DOCKERHUB_PASSWORD       
    steps:
      - checkout
      - run:
          name: Running linter
          command: |
            flake8
      - run:
          name: Running tests
          command: |
            python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app
