version: 2.1

workflows:
  heroku_deploy:
    jobs:
      - build_main:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build_main
          filters:
            branches:
              only: main

jobs:
  build_main:
    docker:
      - image: docker:18.09-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install docker-compose
          command: |
            apk add --update py3-pip
            pip3 install docker-compose==1.12.0
      - run:
          name: Build application Docker image from file
          command: |
            docker build -t fortranvba/dap13:dap13prod .
      - run:
          name: Run test
          command: |
            docker-compose -f ./docker-compose.test.yml up
      - store_artifacts:
          path: test-reports/
          destination: python_app
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u fortranvba -p $DOCKERHUB_PASSWORD
            docker push fortranvba/dap13:dap13prod
  deploy:
    docker:
      - image: fortranvba/dap13:dap13prod
        auth:
          username: fortranvba
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            su -
            apt-get install sudo -y
            sudo apt install git-all
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
