version: 2
jobs:
  build:
    docker:
      - image: fortranvba/dap13:dap13prod
        auth:
          username: fortranvba
          password: $DOCKERHUB_PASSWORD       
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running linter
          command: |
            . venv/bin/activate
            flake8
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app
