version: 2.1

workflows:
  heroku_deploy:
    jobs:
      - build_main:
          filters:
            branches:
              only: main
      - build_test:
          filters:
            branches:
              ignore: main
      - heroku_deploy:
          requires:
            - build_main
          filters:
            branches:
              only: main


jobs:
  build_main:
    docker:
      - image: docker:18.09-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install docker-compose
          command: |
            apk add --update py3-pip
            pip3 install docker-compose==1.12.0
      - run:
          name: Build application Docker image from file
          command: |
            docker build -t fortranvba/dap13:dap13prod .
      - run:
          name: Run test
          command: |
            docker-compose -f ./docker-compose.test.yml up
      - store_artifacts:
          path: test-reports/
          destination: python_app
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u fortranvba -p $DOCKERHUB_PASSWORD
            docker push fortranvba/dap13:dap13prod
  build_test:
    docker:
      - image: fortranvba/dap13:dap13prod
    steps:
      - checkout
      - run:
          name: Run test
          command: |
            flake8
            python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app
  heroku_deploy:
    docker:
      - image: fortranvba/dap13:dap13prod
    steps:
      - checkout
      - run:
          name: Build and push docker image to heroku
          command: |
            set -x
            curl https://cli-assets.heroku.com/install.sh | sh
            pip install docker
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a oc-lettings-mpyf web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a oc-lettings-mpyf web
